# Generated by Django 2.2.4 on 2021-05-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car',
        ),
    ]
