# Generated by Django 2.2.4 on 2021-05-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message_text',
            new_name='comment_text',
        ),
    ]
