# Generated by Django 2.2.4 on 2021-05-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0004_auto_20210528_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(null=True),
        ),
    ]
