# Generated by Django 2.2.4 on 2021-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0005_auto_20210528_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='new comment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(default='new message'),
        ),
    ]
