# Generated by Django 2.2.4 on 2021-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_publisher_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=200, max_length=255),
        ),
    ]
