# Generated by Django 2.2.4 on 2021-05-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0002_auto_20210522_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
